export const copy = {
  gateHeading: "Парола за преглед",
  gateHint: "За Иван и Десислава. Не е за гостите.",
  passwordField: "Парола",
  gateSubmit: "Отвори снимките",
  gateError: "Грешна парола.",
  galleryTitle: "Снимки от гостите",
  gallerySubtitle: "Какво са изпратили гостите. Премахнете само ако трябва.",
  logout: "Затвори достъпа",
  empty: "Все още няма качени снимки.",
  loadMore: "Още снимки",
  removeAria: "Премахни снимката",
  viewFullAria: "Виж на цял екран",
  closeFullAria: "Затвори снимката",
  confirmBody: "Да премахнем ли тази снимка? Няма връщане назад.",
  confirm: "Премахни",
  cancel: "Остави я",
  removeError: "Не успяхме да премахнем снимката.",
} as const;
